GET http://localhost:3001

### get all asiakkaat
GET http://localhost:3001/api/asiakas

### get one existing asiakas
GET http://localhost:3001/api/asiakas/1

### get one missing asiakas
GET http://localhost:3001/api/asiakas/99999

### create asiakas
POST http://localhost:3001/api/asiakas
content-type: application/json

{
    "nimi": "Aleksi", 
    "puhelinnumero": "0508673232", 
    "katuosoite": "Jokukatu 12 c 3", 
    "postinumero": 42353, 
    "postitoimipaikka": "Askola"
}

### send wrong json
POST http://localhost:3001/api/asiakas
content-type: application/json

{
    "nimi": 123, 
    "puhelinnumero": "0508673232", 
    "katuosoite": "Jokukatu 12 c 3", 
    "postinumero": 42353, 
    "postitoimipaikka": "Askola"
}